### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'SimpleModal')" on latest SteamUI update with 0.1.4-1

### ISSUE THREAD

**Issue by eXhumer** [FlashyReese/decky-wine-cellar#12]
Updated SteamUI today (27th February 2024) and Wine Cellar has stopped working with the above mentioned error message while trying to access the Wine Cellar UI from Decky Sidebar Menu. I am currently on release branch of Steam, stable channel of decky-loader (v2.11.1) and using the default store channel in decky-loader. This is due to outdated DLF package being used (v3.23.1), using the current version (v.3.24.5) fixes the issue.

**Comment by PS2ClassicsVault** [comment]
me too having the same error as well!

**Comment by japzone1** [comment]
Yeah, broke with latest stable SteamOS and Decky Loader versions. Reading the issues on Decky Loader looks like plugins need to update DFL to v3.19.1+ in order to be compatible now.

**Comment by Heaven-Crow** [comment]
How do I update the DFL package? Sorry, I'm new to this.

**Comment by japzone1** [comment]
> How do I update the DFL package? Sorry, I'm new to this.

The plugin developer has to do it, not the users.

**Comment by W13N3N** [comment]
I'm having the same issue

**Comment by gnarTriip** [comment]
Same issue here. I'm on steam beta release and it's been doing this for a while now

**Comment by CEOofUnhandledExceptions** [comment]
Has been broken for weeks. This plugin just dead? It'd be a massive shame

**Comment by Velgus** [comment]
> Has been broken for weeks. This plugin just dead? It'd be a massive shame

The repo maintainer [FlashyReese](https://github.com/FlashyReese) has in their profile:

> 📅 I'm currently away for the next four months

**Comment by martpendle** [comment]
This is now resolved with the latest version I think this can be closed

**Comment by PS2ClassicsVault** [comment]
I will have to assess this when i get home
